### ISSUE TITLE
[BUG] 초기 앱 꺼짐 현상

### ISSUE THREAD

**Issue by HI-JIN2** [EAT-SSU/Android#236]
# ⚠️ Bug Report

## 발견한 문제

> 정확한 문제와 상황을 적어주세요. 나중에 개발자가 다시 시연하기 편하게 상황까지 적어주시면 좋습니다.

![image](https://github.com/user-attachments/assets/72fac6d8-5de5-427a-bace-0d36ad1d1b6a)

## 스크린샷

> 텍스트로 설명하기 어렵거나 편하게 이해하기 위해서는 발생한 문제의 스크린샷이나 동영상을 남겨주세요.

## 플랫폼(Android)

- 디바이스: 

## 기타 정보

- 앱 버전:

**Comment by kangyuri1114** [comment]
제가 토큰인터셉터 코드를 봤는데 이 문제인 것 같아요

- `Timber.e("재발급에서의 401")`
- `Toast.makeText(context, "토큰이 만료되어 로그아웃 됩니다.", Toast.LENGTH_SHORT).show()`

위 로그와 토스트는 잘 뜨고 강제 종료 됨

그때 로그

```
FATAL EXCEPTION: OkHttp Dispatcher
Process: com.eatssu.android, PID: 19398
java.lang.IllegalStateException: closed
at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:247)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
at java.lang.Thread.run(Thread.java:1119)
```

[우리랑 비슷한 상황? 인거같은 레퍼런스](https://velog.io/@yongin01/Android-OkHTTP3-%EC%9D%B8%ED%84%B0%EC%85%89%ED%8A%B8-%EC%8A%A4%ED%8A%B8%EB%A6%BC-%EC%98%A4%EB%A5%98-%ED%95%B4%EA%B2%B0%ED%95%98%EA%B8%B0Exception-java.lang.IllegalStateException-closed)

**[ 내 추정... ]**
- 401이 발생하면 `TokenInterceptor`에서 토스트를 띄우고 `LoginActivity`로 이동시키지만
- 앱은 로그인 화면으로 안 가고 **강제 종료 (FATAL EXCEPTION)** 됨
- 로그에 `java.lang.IllegalStateException: closed` 발생
- 그 후 `SIG: 9`로 앱 강제 종료됨

`HttpLoggingInterceptor`가 **이미 닫힌 ResponseBody를 읽으려고 함**
하지만 그 이후에도 `return response`가 호출됨

 84번째 줄 보면 401로 가서 response.close() 닫았는데 

함수 맨 마지막에 response를 return 해서 강종되는 듯

-> 이 해결책으로 생각나는 건 더미 response를 만들어야 할까? 인데.. 과연 좋은 방법일지 고민됩니다..
